name: digibyte-core
version: '7.17.3'
summary:   Decentralized peer-to-peer based digital currency
description: |
  DigiByte is a rapidly growing open-source blockchain created in late 2013
  and released in early 2014. After 8 years of forward-thinking development,
  DigiByte has become one of the safest, fastest, longest, and most
  decentralized UTXO blockchains in existence.

grade: stable
confinement: strict

apps:
  daemon:
    command: digibyted
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at
      # ~/snap/digibyte-core/common/.digibyte/ instead of
      # ~/snap/digibyte-core/current/.digibyte/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch digibyte-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: digibyte-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  digibyte-core:
    plugin: nil
    override-build: |
      env | grep SNAP
      wget  https://github.com/DigiByte-Core/digibyte/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/digibyte-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      wget https://github.com/DigiByte-Core/digibyte/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/digibyte-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      tar -xvf digibyte-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      tar -xvf digibyte-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      echo "Running tests ..."
      digibyte-${SNAPCRAFT_PROJECT_VERSION}/bin/test_digibyte
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin digibyte-${SNAPCRAFT_PROJECT_VERSION}/bin/digibyted
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin digibyte-${SNAPCRAFT_PROJECT_VERSION}/bin/digibyte-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin digibyte-${SNAPCRAFT_PROJECT_VERSION}/bin/digibyte-cli
      wget https://raw.githubusercontent.com/DigiByte-Core/digibyte/v${SNAPCRAFT_PROJECT_VERSION}/share/pixmaps/digibyte128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps digibyte128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
